openapi: 3.0.1
info:
  title: Vision10 API Documentation
  description: V10 open API document.
  version: 1.0.0
servers:
- url: http://204.105.107.65:24500/fva_apac/
paths:
  /v1/transactions/lastStatement:
    get:
      tags:
      - Transaction APIs
      x-group-name:  "Transaction Management"
      x-proxy-name:  "Inquire Transaction Details"
      summary: Transaction details
      description: "Provides transaction detail information from the last billing cycle"
      operationId: Transaction details
      parameters:
      - name: X-Correl-Id
        in: header
        description: Any correlational text client's may want to send in the request for mapping the response on their side. Any value passed in the request message will be return back as-is in the API response message
        schema:
          maxLength: 40
          minLength: 0
          type: string
          example: EXC-ID-12345678-SUB
      - name: X-Name
        in: header
        required: true
        description: Userâ€™s sign-on name. The value passed in this field will be validated within application for user's authority to consume the requested API
        schema:
          maxLength: 20
          minLength: 0
          type: string
          example: John
      - name: X-context
        in: header
        required: true
        description: A unique random ID assigned to the requestor once authenticated to the First Vision application. Value passed in this field will be used within application to authenticate the valid signed-on user
        schema:
          maxLength: 20
          minLength: 0
          type: string
          example: 00001AUVMX
      - name: businessUnit
        in: query
        description : "Business Unit - Identification number associated with this Account Base Segment record."
        schema:
          type: number
          default: 0.0
          example: 100
      - name: accountNumber
        in: query
        description : "Account Number - Unique Identification number of the Account."
        schema:
          maxLength: 19
          type: string
          format: uppercase
          example: 100001NNNXX0481
      - name: product
        in: query
        description: "Product - Identification number of the product associated with the Account"
        schema:
          type: number
          default: 0
          example: 1
      - name: statementDate
        in: query
        description: "Statement Date - Period for which the user want to view the important statement details of the Account"
        schema:
          type: string
          format: date
          example: 04/09/2021

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LastStatementResponse'
              examples: 
                TransactionalDetails: {$ref: '#/components/examples/StatementResponse'}
        400:
          description: The request cannot be validated
          content:
            application/json:
              schema: {$ref: '#/components/schemas/ErrorList'}
              example:
                400:
                  $ref: '#/components/examples/400-Errors'
        401:
          description: The request was unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
                401:
                  $ref: '#/components/examples/401-Errors'
        404:
          description: The request resource does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
                404:
                  $ref: '#/components/examples/404-Errors'
        500:
          description: An unexpected internal server error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
                500:
                  $ref: '#/components/examples/500-Errors'
        503:
          description: The service was unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
                503:
                  $ref: '#/components/examples/503-Errors'
        504:
          description: The request timed out while waiting for a response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
                504:
                  $ref: '#/components/examples/504-Errors'                      
components:
  schemas:
    LastStatementResponse:
      required: 
      - businessUnit
      - accountNumber
      type: object
      properties:
        statementDate:
          type: string
          format: date
          example: 04/09/2021
          description: "Statement Date - Period for which the user want to view the important statement details of the Account"
        account/Relationship:
          maxLength: 19
          type: string
          example: 0002XX001NNN0001211
          description: "Identification number of the account"
        fileType:
          maxLength: 2
          type: string
          example: XXX
          description: "Type of file. Small Statement or Large Statement"
    
        transactionList:
          type: array
          items:
              type: object
              properties:
                effectiveDate:
                  type: string
                  format: date
                  example: 03/26/2021
                  description: "Effective date of the transaction."
                postingDate:
                  type: string
                  format: date
                  example: 03/26/2021
                  description: "Posting date of the transaction."
                transactionType:
                  maxLength: 1
                  type: string
                  example: X
                  description: "Transaction type that identifies the type of transaction. The values are D (debit), C (credit), and M (memo)"
                description: 
                  maxLength: 40
                  type: string
                  example: XXXX XXXX XXXX NNNNN
                  description: "Description of the Transaction"
                amount: 
                  type: string
                  default: 0
                  example: $XX.XX
                  description: "Amount of the transaction"
                transactionCode:
                  type: string
                  default: 0
                  example: NNNN
                  description: "Transaction Code associated with the transaction"
                logicModule: 
                  type: number
                  default: 0
                  example: X
                  description: "Logic module associated with the transaction code"
                creditPlan:
                  type: number
                  default: 0
                  example: 12345
                  description: "Number that identifies the Credit Plan Master record for the credit plan to which the transaction was posted"
                reference:
                  type: string
                  maxLength: 23
                  example: 199NNNNNN80326199980140
                  description: "Reference number assigned to the transaction"
                authorizationCode:
                  type: string
                  maxLength: 6
                  example: " "
                  description: "Authorization code assigned to the transaction"
                aMSLKey:
                  type: string
                  maxLength: 34
                  example: " " 
                  description: "Key of the record"
                recordNumber:  
                  type: string
                  default: 0
                  maximum: 99999
                  example: XX
                  description: "Sequence Number of the transaction"
                logo: 
                  type: number
                  default: 0
                  maximum: 999
                  example: X
                  description: "Number that identifies the logo associated with the account"
                businessUnit:
                  type: number
                  default: 0
                  maximum: 999
                  example: 100
                  description: "Business Unit - Identification number associated with this Account Base Segment record"
      
        tranNextToken:
          type: string
          maxLength: 40
          example: 200000200001NNNNNNN1211202109y50052
          description: "Next Token for transaction series"
        tranPrevToken:
          type: string
          maxLength: 40
          example: 200000200001NNNNNNNN1211202109y50003
          description: "Previous Token for transaction series"
        tableIND:
          type: string
          maxLength: 1
          example: " "
          description: "Table Indicator"
        hiddenKey:
          type: string
          maxLength: 80
          example: " "
        planNextTokenlast:
          type: string
          maxLength: 80
          example: " "
          description: "Next Token for transaction series"
        planPREVTokenlast:
          type: string
          maxLength: 80
          example: " "
          description: "Previous Token for Plan series" 
        cPLastFunc:
          type: string
          maxLength: 1
          example: " "
          description: "Credit Plan last function"
    
    ErrorList:
      type: array
      items:
        type: object
        properties:
          errorCode:
            type: string
            example:  XXXXXXXX
            description: Error code associated with the response
          errorMessage:
            type: string
            example: Some message from the service
            description: Error message associated with the response
  examples:
    StatementResponse: 
      value: { 
        planNextTokenlast: '', 
        tableIND: '', 
        recordNumber: 52,
        amount: '$30.83', 
        businessUnit : 200 ,
        authorizationCode : '', 
        description : 'DEBIT CARD OFFSET CREDIT', 
        postingDate : '03/26/2021', 
        transactionCode : '7016', 
        aMSLKey : '', 
        reference : '19999999980326199980140',
        transactionType: C, 
        creditPlan : 10002, 
        logo : 1 , 
        logicModule: 4, 
        effectiveDate : '03/26/2021', 
        tranPrevToken : '2000002000010000001211202109y50003',
        cPLastFunc : '', 
        tranNextToken: '2000002000010000001211202109y50052',
        accountRelationship: '0002000010000001211',
        statementDate: '04/09/2021', 
        hiddenKey: '',
        planPREVTokenlast: '', 
        fileType: '',
      "transactionList" : [{
        recordNumber : 52,
        amount : '$30.83',
        businessUnit: 200,
        authorizationCode: '',
        description: 'DEBIT CARD OFFSET CREDIT',
        postingDate: 03/26/2021,
        transactionCode: '7016',
        aMSLKey: '',
        reference: '19999999980326199980140',
        transactionType: C,
        creditPlan: 10002,
        logo: 1,
        logicModule: 4,
        effectiveDate: '03/26/2021'
        
      }
        ]  
      }
  
    400-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    401-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    404-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    500-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    503-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    504-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
