openapi: 3.0.1
info:
  title: Vision10 API Documentation
  description: V10 open API document.
  version: 1.0.0
servers:
- url: http://204.105.107.65:24500/fva_apac/
paths:
  /v1/accounts/blockUnblock:
    patch:
      tags:
        - Account Management
      x-group-name: Account Management
      x-proxy-name: Block-Unblock Account
      summary: Block-Unblock Account
      description: This service is used to update the Account Block Code
      operationId: blockUnblock
      parameters:
      - name: X-Correl-Id
        in: header
        example: ABC123
        description: Any correlational text client's may want to send in the request for mapping the response on their side. Any value passed in the request message will be return back as-is in the API response message
        schema:
          maxLength: 40
          minLength: 0
          type: string
          
      - name: X-Name
        in: header
        required: false
        example: 00001AUVMA
        description: User’s sign-on name. The value passed in this field will be validated within application for user's authority to consume the requested API
        schema:
          maxLength: 30
          minLength: 0
          type: string
          
      - name: X-context
        in: header
        required: true
        example: 00001AUVMA
        description: A unique random ID assigned to the requestor once authenticated to the First Vision application. Value passed in this field will be used within application to authenticate the valid signed-on user
        schema:
          maxLength: 20
          minLength: 0
          type: string
          
          
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountsBlockUnblockReq'
            examples: 
              BlockAccount: {$ref: '#/components/examples/BlockAccount'}
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountsBlockUnblockResp'
              examples: 
                BlockAccount: {$ref: '#/components/examples/BlockAccountResp'}
                                  
        400:
          description: The request cannot be validated
          content:
            application/json:
              schema: {$ref: '#/components/schemas/ErrorList'}
              example:
                400:
                  $ref: '#/components/examples/400-Errors'
        401:
          description: The request was unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
                401:
                  $ref: '#/components/examples/401-Errors'
        404:
          description: The request resource does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
                404:
                  $ref: '#/components/examples/404-Errors'
        500:
          description: An unexpected internal server error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
                500:
                  $ref: '#/components/examples/500-Errors'
        503:
          description: The service was unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
                503:
                  $ref: '#/components/examples/503-Errors'
        504:
          description: The request timed out while waiting for a response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
                504:
                  $ref: '#/components/examples/504-Errors'
              
components:
  schemas:
    AccountsBlockUnblockReq:
      required:
      - product
      - billingAcctInd
      - businessUnit
      - accountNumber
      type: object
      properties:
        businessUnit:
          type: number
          default: 0.0
          example: 100
          description: Business Unit -Identification number of the organization associated with thisAccount Base Segment record. The values are 001–998
        accountNumber:
          type: string
          maxLength: 19
          format: uppercase
          example: 100001NNNNN0481
          description: Account- Customer account number. Must be numeric and greater than zero. Max length = 19. Should be a valid Account number.
        product:
          type: number
          example: 001
          description: Product associated with this Account. The values are 001–998
        billingAcctInd:
          type: number
          example: 0
          description: ACCOUNT TYPE-Code that indicates whether the account being
            added is atransaction (cardholder), billing, control, or diversion account
        blockCode1:
          type: string
          example: X
          description: Block code 1-Field that identifies the block codes assigned to this account. Block codes control specific processing options at theaccount level. Valid block codes are the letters A to Z and spaces
        blockCode2:
          type: string
          example: " "
          description: Block code 2-Field that identifies the block codes assigned to this account. Block codes control specific processing options at theaccount level. Valid block codes are the letters A to Z and spaces
    AccountsBlockUnblockResp:
      required:
      - accountNumber
      - billingAcctInd
      - businessUnit
      - product
      type: object
      properties:
        product:
          type: number
          example: 1
          description: Product associated with this Account. The values are 001–998
        businessUnit:
          type: number
          example: 100
          description: 'Business Unit -Identification number of the organization associated
            with thisAccount Base Segment record. The values are 001–998 '
        accountNumber:
          maxLength: 19
          type: string
          example: 100001NNNXX0481
          description: Account- Customer account number. Must be numeric and greater
            than zero. Max length = 19. Should be a valid Account number.
          format: uppercase
        billingAcctInd:
          type: number
          example: 0
          description: ACCOUNT TYPE-Code that indicates whether the account being
            added is atransaction (cardholder), billing, control, or diversion account
        blockCode1:
          type: string
          example: X
          description: Block code 1-Field that identifies the block codes assigned to this account. Block codes control specific processing options at theaccount level. Valid block codes are the letters A to Z and spaces
        blockCode2:
          type: string
          example: " "
          description: Block code 2-Field that identifies the block codes assigned to this account. Block codes control specific processing options at theaccount level. Valid block codes are the letters A to Z and spaces
        blockCodeDate1:
          type: string
          format: uppercase
          example: 01/10/2021
          description: BLOCK DATE 1-Date on which block code 1 was entered. The value in this fieldis system-generated; you cannot change it
        blockCodeDate2:
          type: string
          format: uppercase
          example: 00/00/0000
          description: BLOCK DATE 2-Date on which block code 1 was entered. The value in this fieldis system-generated; you cannot change it
    ErrorList:
      type: array
      items:
        type: object
        properties:
          errorCode:
            type: string
            example:  XXXXXXXX
            description: Error code associated with the response
          errorMessage:
            type: string
            example: Some message from the service
            description: Error message associated with the response
  examples:
    BlockAccount:
      value: { businessUnit: 100, accountNumber: '0001000010000510481', product: 001, billingAcctInd: 0, blockCode1: 'X' }
    BlockAccountResp:
      value: {
        businessUnit: 100, accountNumber: '0001000010000510481', product: 1, billingAcctInd: 0, blockCode1: X, blockCodeDate1: '01/10/2021', blockCode2: ' ', blockCodeDate2: '00/00/0000'  }
    400-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    401-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    404-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    500-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    503-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    504-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
