openapi: 3.0.1
info:
  title: Vision10 API Documentation
  description: V10 open API document.
  version: 1.0.0
  contact:
    name: "Fiserv"
servers:
- url: 'https://stg34.visionplus.io:24500'
tags:
 - name: "Customer Management"
paths:
  /v1/customers/nameAddress:
    get:
      tags:
      - Customer Management
      x-group-name: Customer Management
      x-proxy-name:  Customer Demographic Inquiry
      summary:  Customer Demographic Inquiry
      description: This service will be used to enquire the customer demographic details such as Name / Address / Phone Number / Email ID/ Date of Birth of the given customer. The customer ID will be passed in the input request to retrieve the demographic information.
      operationId: nameAddress
      parameters:
      - name: X-Correl-Id
        in: header
        description: Any correlational text client's may want to send in the request for mapping the response on their side. Any value passed in the request message will be return back as-is in the API response message
        schema:
          maxLength: 40
          minLength: 0
          type: string
          example: EXC-ID-12345678-SUB
      - name: X-Name
        in: header
        required: true
        description: User’s sign-on name. The value passed in this field will be validated within application for user's authority to consume the requested API
        schema:
          maxLength: 20
          minLength: 0
          type: string
          example: John 
      - name: X-context
        in: header
        required: true
        description: A unique random ID assigned to the requestor once authenticated to the First Vision application. Value passed in this field will be used within application to authenticate the valid signed-on user
        schema:
          maxLength: 20
          minLength: 0
          type: string
          example: 00001AUVMX
      - name: businessUnit
        in: query
        required: true
        description : "Business Unit -Identification number of the organization associated with thisAccount Base Segment record. The values are 001–998."
        schema:
          type: number
          default: 0.0
          example: 100
      - name: accountNumber
        in: query
        required: true
        description : "Must be numeric and greater than zero. Max length = 19. Should be a valid customer number."
        schema:
          maxLength: 19
          type: string
          format: uppercase
          example: 100001NNNXX0481
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerAddressResponse'
              examples: 
                AddressInquiry: {$ref: '#/components/examples/AddressInquiryResponse'}  
        '400':
          description: The request cannot be validated
          content:
            application/json:
              schema: {$ref: '#/components/schemas/ErrorList'}
              example:
               - '400':
                    $ref: '#/components/examples/400-Errors'
        '401':
          description: The request was unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
               - '401':
                    $ref: '#/components/examples/401-Errors'
        '404':
          description: The request resource does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
               - '404':
                  $ref: '#/components/examples/404-Errors'
        '500':
          description: An unexpected internal server error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
               - '500':
                  $ref: '#/components/examples/500-Errors'
        '503':
          description: The service was unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
               - '503':
                    $ref: '#/components/examples/503-Errors'
        '504':
          description: The request timed out while waiting for a response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
                - '504':
                    $ref: '#/components/examples/504-Errors'        
    patch:
      tags:
      - Customer Management
      x-group-name: Customer Management
      x-proxy-name:  Customer Demographic Update
      summary:  Customer Demographic Update
      description: This service will be used to update the customer demographic details such as Name / Address / Phone Number / Email ID/ Date of Birth of the given customer. The customer ID will be passed in the input request to retrieve the demographic information.
      operationId: customersNameAddress
      parameters:
      - name: X-Correl-Id
        in: header
        description: Any correlational text client's may want to send in the request for mapping the response on their side. Any value passed in the request message will be return back as-is in the API response message
        schema:
          maxLength: 40
          minLength: 0
          type: string
          example: EXC-ID-12345678-SUB
      - name: X-Name
        in: header
        required: true
        description: User’s sign-on name. The value passed in this field will be validated within application for user's authority to consume the requested API
        schema:
          maxLength: 20
          minLength: 0
          type: string
          example: John Smith
      - name: X-context
        in: header
        required: true
        description: A unique random ID assigned to the requestor once authenticated to the First Vision application. Value passed in this field will be used within application to authenticate the valid signed-on user
        schema:
          maxLength: 20
          minLength: 0
          type: string
          example: 00001AUVMX
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerAddressUpdateReq'
            examples: 
              AddressUpdate: {$ref: '#/components/examples/AddressUpdateReq'}
      

      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerAddressUpdateResponse'
              examples: 
                AddressUpdate: {$ref: '#/components/examples/AddressUpdateResponse'}  
        '400':
          description: The request cannot be validated
          content:
            application/json:
              schema: {$ref: '#/components/schemas/ErrorList'}
              example:
               - '400':
                    $ref: '#/components/examples/400-Errors'
        '401':
          description: The request was unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
               - '401':
                    $ref: '#/components/examples/401-Errors'
        '404':
          description: The request resource does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
               - '404':
                    $ref: '#/components/examples/404-Errors'
        '500':
          description: An unexpected internal server error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
               - '500':
                    $ref: '#/components/examples/500-Errors'
        '503':
          description: The service was unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
               - '503':
                    $ref: '#/components/examples/503-Errors'
        '504':
          description: The request timed out while waiting for a response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
               - '504':
                    $ref: '#/components/examples/504-Errors'                     
components:
  schemas:
    CustomerAddressResponse:
      required:
      - accountNumber
      - businessUnit
      type: object
      properties:
        nameLine31:
          maxLength: 40
          type: string
          format: uppercase
          example: " "
          description: "NAME-LINE 3-this field is a code that indicates the type ofname. This untitled field displays to the right of the NAME LINE 3field. The values arefields are 0=Personal name (Default),1=Business name,3 = gender name"
        nameLine11:
          maxLength: 40
          type: string
          format: uppercase
          example: " "
          description: "NAME-LINE 1-This field is the owner personal name, businessname, or a generic name. If the name is a personal name(type)this field displays the contents of the FIRST NAME, MIDDLENAME, and LAST NAME fields The name tyep fields are 0=Personal name (Default),1=Business name,3 = gender name"
        nameLine21:
          maxLength: 40
          type: string
          format: uppercase
          example: " "
          description: "NAME-LINE 2-this field is the owner name. You must enternames in the correct format as defined in the Organization"
        businessUnit:
          type: number
          example: 100
          description: "Business Unit -Identification number of the organization associated with thisAccount Base Segment record. The values are 001–998."
        accountNumber:
          maxLength: 19
          type: string
          format: uppercase
          example: 100001NNNXX0481
          description: "Must be numeric and greater than zero. Max length = 19. Should be a valid customer number."
        houseNumber1:
          maxLength: 20
          type: string
          format: uppercase
          example: " "
          description: "HOUSE NAME-House name of the owner. The default is spaces"
        addressLine11:
          maxLength: 40
          type: string
          format: uppercase
          example: X.ANGLES
          description: "Address Line 1-Mailing address for the owner"  
        addressLine21:
          maxLength: 40
          type: string
          format: uppercase
          example: " "
          description: "Address Line 2-Mailing address for the owner"
        addressLine31:
          maxLength: 40
          type: string
          format: uppercase
          description: "Address Line 3-Mailing address for the owner"
        addressLine41:
          maxLength: 40
          type: string
          format: uppercase
          example: " "
          description: "Address Line 4-Mailing address for the owner"
        city1:
          maxLength: 30
          type: string
          format: uppercase
          example: X
          description: "City-City portion of the mailing address of the owner"
        stateProvince1:
          maxLength: 3
          type: string
          format: uppercase
          example: X
          description: "State/Province-Abbreviation of the state or province portion of the mailingaddress of the owner"
        countryCode1:  
          maxLength: 3
          type: string
          format: uppercase
          example: X
          description: "Country Code-Thevalue entered must be a valid country code previously definedin the Security Subsystem and Common Routines (SSC) system"
        postalCode1:
          maxLength: 10
          type: string
          format: uppercase
          example: 2NN99
          description: "Postal Code-Postal code portion of the mailing address of the owner" 
        languageIndicator1:
          maxLength: 3
          type: string
          format: uppercase
          example: NNN
          description: "Language Indicator-User-defined code that indicates the language spoken by theowner."
        homePhoneNumber1:
          maxLength: 20
          type: string
          format: uppercase
          example: "1111235464447576"
          description: "Home Phone Number-that indicates the home telephone number ofthe owner"
        homePhoneFlag1:
          type: string
          example: "0"
          description: "Home Phone Flag-this field is a code that specifies whether theyou have the owner’s permission to call this number. The values 0 =No, do not contact the customer at this number,1=Yes, you can contact the customer at thisnumber (Default) 2=Preferred contact method" 
        faxNumber1:
          type: string
          example: " "
          description: "Fax Number-field that indicates the facsimile (fax) number of theowner"
        faxPhoneFlag1:
          type: string
          example: "0"
          description: "Fax Phone Flagthis field is a code that specifies whether theyou have the owner’s permission to call this number. The values 0 =No, do not contact the customer at this number,1=Yes, you can contact the customer at thisnumber (Default) 2=Preferred contact method" 
        mobileNumber1:
          maxLength: 20
          type: string
          format: uppercase
          example: "11110976234"
          description: "Mobile Number-that indicates the mobile telephone number ofthe owner"
        sMSFlag1:
          type: string
          example: "1"
          description: "SMS Flag-Code that indicates whether an SMS (short message service)message can be sent to the owner. The values are 0=No, do not contact the customer via SMS, 1=Yes, you can contact the customer via SMS(Default)"
        mobilePhoneFlag1: 
          type: string
          example: "0"
          description: "Mobile Phone Flag-this field is a code that indicates whether youhave the owner’s permission to call this number. The values are0 =No, do not contact the customer at this number,1=Yes, you can contact the customer at thisnumber (Default) 2=Preferred contact method"
        emailAddress1:  
          maxLength: 60
          type: string
          format: uppercase
          example: ABC@GMAIL
          description: "Email-that indicates the e-mail address of the owner"
    CustomerAddressUpdateResponse:
      required:
      - accountNumber
      - businessunit
      type: object
      properties:
        businessunit:
          type: number
          example: 100
          description: "Business Unit -Identification number of the organization associated with thisAccount Base Segment record. The values are 001–998."
        accountNumber:
          maxLength: 19
          type: string
          format: uppercase
          example: 100001NNNNN0481
          description: "CUSTOMER NUMBER - Must be numeric and greater than zero. Max length = 19. Should be a valid customer number."
        nameLine11:
          maxLength: 40
          type: string
          format: uppercase
          example: " " 
          description: "NAME-LINE 1-This field is the owner personal name, businessname, or a generic name. If the name is a personal name(type)this field displays the contents of the FIRST NAME, MIDDLENAME, and LAST NAME fields The name tyep fields are 0=Personal name (Default),1=Business name,3 = gender name"  
        nameLine21:
          maxLength: 40
          type: string
          format: uppercase
          example: " "
          description: "NAME-LINE 2-this field is the owner name. You must enternames in the correct format as defined in the Organization"
        nameLine31:
          maxLength: 40
          type: string
          format: uppercase
          example: " "
          description: "NAME-LINE 3-this field is a code that indicates the type ofname. This untitled field displays to the right of the NAME LINE 3field. The values arefields are 0=Personal name (Default),1=Business name,3 = gender name"
        houseNumber1:
          maxLength: 20
          type: string
          format: uppercase
          example: " "
          description: "HOUSE NAME-House name of the owner. The default is spaces"
        addressLine11:
          maxLength: 40
          type: string
          format: uppercase
          example: X.ANGLES
          description: "Address Line 1-Mailing address for the owner"
        addressLine21:
          maxLength: 40
          type: string
          format: uppercase
          example: " "
          description: "Address Line 2-Mailing address for the owner"
        addressLine31:
          maxLength: 40
          type: string
          format: uppercase
          example: " "
          description: "Address Line 3-Mailing address for the owner"
        addressLine41:
          maxLength: 40
          type: string
          format: uppercase
          example: " "
          description: "Address Line 4-Mailing address for the owner"
        city1:
          maxLength: 30
          type: string
          format: uppercase
          example: XXX
          description: "City-City portion of the mailing address of the owner"
        stateProvince1:
          maxLength: 3
          type: string
          format: uppercase
          example: XXX
          description: "State/Province-Abbreviation of the state or province portion of the mailingaddress of the owner"
        countryCode1:
          maxLength: 3
          type: string
          format: uppercase
          example: XXX
          description: "Country Code-Thevalue entered must be a valid country code previously definedin the Security Subsystem and Common Routines (SSC) system"
        postalCode1:
          maxLength: 10
          type: string
          format: uppercase
          example: "12345"
          description: "Postal Code-Postal code portion of the mailing address of the owner"
        languageIndicator1:
          maxLength: 3
          type: string
          format: uppercase
          example: XXX
          description: "Language Indicator-User-defined code that indicates the language spoken by theowner."
        homePhoneNumber1:
          maxLength: 20
          type: string
          format: uppercase
          example: "12345678989898"
          description: "Home Phone Number-that indicates the home telephone number ofthe owner"
        homePhoneFlag1:
          type: string
          enum:
          - '0'
          - '1'
          - '2'
          example: '0'
          description: "Home Phone Flag-this field is a code that specifies whether theyou have the owner’s permission to call this number. The values 0 =No, do not contact the customer at this number,1=Yes, you can contact the customer at thisnumber (Default) 2=Preferred contact method"
        faxNumber1:
          maxLength: 20
          type: string
          format: uppercase
          example: " "
          description: "Fax Number-field that indicates the facsimile (fax) number of theowner"
        faxPhoneFlag1:
          type: string
          enum:
          - '0'
          - '1'
          - '2' 
          example: '1'
          description: "Fax Phone Flagthis field is a code that specifies whether theyou have the owner’s permission to call this number. The values 0 =No, do not contact the customer at this number,1=Yes, you can contact the customer at thisnumber (Default) 2=Preferred contact method"
        mobileNumber1:
          maxLength: 20
          type: string
          format: uppercase
          example: "12345678901"
          description: "Mobile Number-that indicates the mobile telephone number ofthe owner"
        sMSFlag1:
          type: string
          enum:
          - '0'
          - '1'
          example: '1'
          description: "SMS Flag-Code that indicates whether an SMS (short message service)message can be sent to the owner. The values are 0=No, do not contact the customer via SMS, 1=Yes, you can contact the customer via SMS(Default)"
        mobilePhoneFlag1:
          type: string
          enum:
          - '0'
          - '1' 
          - '2'
          example: '1'
          description: "Mobile Phone Flag-this field is a code that indicates whether youhave the owner’s permission to call this number. The values are0 =No, do not contact the customer at this number,1=Yes, you can contact the customer at thisnumber (Default) 2=Preferred contact method"
        emailAddress1:
          maxLength: 60
          type: string
          format: uppercase
          example: ABC@GMAIL
          description: "Email-that indicates the e-mail address of the owner"
    CustomerAddressUpdateReq:
      required:
      - accountNumber
      - businessunit
      - homePhoneNumber1
      - mobileNumber1
      - emailAddress1
      type: object
      properties:
        businessunit:
          type: number
          example: 100
          description: "Business Unit -Identification number of the organization associated with thisAccount Base Segment record. The values are 001–998."
        accountNumber:
          maxLength: 19
          type: string
          format: uppercase
          description: "CUSTOMER NUMBER - Must be numeric and greater than zero. Max length = 19. Should be a valid customer number."
          example: 100001NNNNN0481
        homePhoneNumber1:
          maxLength: 20
          type: string
          format: uppercase
          description: "Home Phone Number-that indicates the home telephone number ofthe owner"
          example: "123456788999346"
        mobileNumber1:
          maxLength: 20
          type: string
          format: uppercase
          description: "Mobile Number-that indicates the mobile telephone number ofthe owner."
          example: "111109701444"
        emailAddress1:
          maxLength: 60
          type: string
          format: uppercase
          description: "Email-that indicates the e-mail address of the owner"
          example: ABC@GMAIL 
    ErrorList:
      type: array
      items:
        type: object
        properties:
          errorCode:
            type: string
            example:  XXXXXXXX
            description: Error code associated with the response
          errorMessage:
            type: string
            example: Some message from the service
            description: Error message associated with the response
  examples:
    AddressInquiryResponse:
      value: { nameLine31: '', nameLine11: '', nameLine21: '' , businessUnit: 100 , accountNumber: '0001000000000150191', houseNumber1: ' ', addressLine11: '80.ANGLES', addressLine21: '', addressLine31: '', addressLine41: '', city1: 'US', stateProvince1: 'USA', countryCode1: 'USA', postalCode1: '27899', languageIndicator1: 'AUS', homePhoneNumber1: '123456788999999', homePhoneFlag1: '0', faxNumber1: '', faxPhoneFlag1: '0', mobileNumber1: '11110976444', sMSFlag1: '0', mobilePhoneFlag1: '0', emailAddress1: 'SAM@GMAIL'}
    AddressUpdateReq:
      value: { businessUnit: 100, accountNumber: '0001000000000150191', homePhoneNumber1: '123456788999999',   mobileNumber1: '11110976444', emailAddress1: 'SAM@GMAIL.COM'}
    
    AddressUpdateResponse:
      value: { businessUnit: 100, accountNumber: '0001000000000150191', nameLine11: '', nameLine21: '', nameLine31: '', houseNumber1: '', addressLine11: '80.ANGLES', addressLine21: '', addressLine31: '', addressLine41: '', city1: 'US', stateProvince1: 'USA', countryCode1: 'USA', postalCode1: '27899', languageIndicator1: 'AUS', homePhoneNumber1: '123456788999999', homePhoneFlag1: '0', faxNumber1: '', faxPhoneFlag1: '0', mobileNumber1: '11110976444', sMSFlag1: '0',mobilePhoneFlag1: '0', emailAddress1: 'SAM@GMAIL' }
    400-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    401-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    404-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    500-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    503-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    504-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
